spring:
  jpa:
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=ReferenceProject;TrustServerCertificate=true;
    username: ${datasource.username}
    password: ${datasource.password}
    activemq:
      broker-url: tcp://localhost:61616
      packages:
        trust-all: true